package com.acme.onboarding.adapter.storage

import com.acme.onboarding.application.document.DocumentStore
import com.acme.onboarding.application.support.NotFoundException
import com.acme.onboarding.config.AcmeProperties
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.stereotype.Component
import java.net.URI
import java.nio.file.Path
import java.time.Duration
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteIfExists
import kotlin.io.path.exists
import kotlin.io.path.readBytes
import kotlin.io.path.writeBytes

/**
 * Filesystem-backed documents, for development and tests.
 *
 * The Cloud Storage adapter is the second implementation of the same port, not a
 * redesign: uploads already go through the application (validated and audited),
 * and downloads already go through an authorized endpoint. What GCS adds is a
 * signed URL instead of a streamed response.
 */
@Component
@ConditionalOnProperty(name = ["acme.storage.provider"], havingValue = "local", matchIfMissing = true)
class LocalDocumentStore(properties: AcmeProperties) : DocumentStore {

    private val root: Path = Path.of(properties.storage.localPath).toAbsolutePath().normalize()

    init {
        root.createDirectories()
    }

    override fun put(key: String, bytes: ByteArray, contentType: String) {
        val path = resolve(key)
        path.parent.createDirectories()
        path.writeBytes(bytes)
    }

    override fun read(key: String): ByteArray {
        val path = resolve(key)
        if (!path.exists()) throw NotFoundException("That file is no longer available.")
        return path.readBytes()
    }

    override fun exists(key: String): Boolean = resolve(key).exists()

    override fun delete(key: String) {
        resolve(key).deleteIfExists()
    }

    /** No signing locally; the caller streams the bytes through the audited endpoint. */
    override fun signedUrl(key: String, ttl: Duration): URI? = null

    /**
     * Keys are generated by the application, never taken from a filename — but
     * this still refuses to escape the root. A path traversal here would turn a
     * document upload into arbitrary filesystem access, and "the caller is
     * trusted" is not a property that survives refactoring.
     */
    private fun resolve(key: String): Path {
        val candidate = root.resolve(key).normalize()
        require(candidate.startsWith(root)) { "Storage key escapes the storage root" }
        return candidate
    }
}
