/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every supplier the caller may see, with what each is blocked on */
        get: operations["list"];
        put?: never;
        /** Start onboarding: create the company, enrol it and invite its first user */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite another person at this supplier */
        post: operations["inviteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document against one requirement */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a password, consume the invitation and sign in */
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign an agreement, producing an executed PDF */
        post: operations["sign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore the seeded demo world */
        post: operations["reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset link */
        post: operations["requestReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset token */
        post: operations["completeReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and receive a session cookie */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email this user a reset link on their behalf */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a deactivated staff member */
        post: operations["reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End a staff member's access immediately */
        post: operations["deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite an Acme staff member */
        post: operations["invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The company profile */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save the company profile */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a staff member's role */
        patch: operations["changeRole"];
        trace?: never;
    };
    "/api/admin/users/{id}/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set which programs a program manager can see */
        patch: operations["setScope"];
        trace?: never;
    };
    "/api/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One supplier's record, with compliance per program */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The people at this supplier who can sign in */
        get: operations["users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this supplier owes, per program, split into on-file and outstanding */
        get: operations["checklist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The supplier's audit timeline, newest first */
        get: operations["activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Acme's client programs */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe an invitation without consuming it */
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a document, recording who read it */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The agreement text and its hash, as shown before signing */
        get: operations["agreement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The demo sign-ins, shown on the sign-in screen */
        get: operations["accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the signed-in user */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The access report: every internal user, role, scope and last sign-in */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/access-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every access change recorded for this user */
        get: operations["accessHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NewSupplierBody: {
            legalName: string;
            contactName: string;
            /** Format: email */
            contactEmail: string;
            programIds: string[];
        };
        BlockerView: {
            /** @enum {string} */
            waitingOn: "SUPPLIER" | "ACME" | "NOBODY";
            summary: string;
            documentTypeCodes: string[];
        };
        EnrollmentView: {
            /** Format: uuid */
            enrollmentId: string;
            /** Format: uuid */
            programId: string;
            programCode: string;
            programName: string;
            status: string;
            /** @enum {string} */
            complianceStatus: "COMPLIANT" | "EXPIRING_SOON" | "NON_COMPLIANT";
            /** Format: date */
            nextExpiry?: string | null;
            findings: components["schemas"]["FindingView"][];
        };
        FindingView: {
            documentTypeCode: string;
            documentTypeName: string;
            /** @enum {string} */
            issue: "MISSING" | "PENDING_REVIEW" | "REJECTED" | "EXPIRED" | "EXPIRING_SOON";
            /** Format: date */
            expiresOn?: string | null;
        };
        SupplierDetail: {
            profile: components["schemas"]["SupplierProfileView"];
            blocker: components["schemas"]["BlockerView"];
            enrollments: components["schemas"]["EnrollmentView"][];
            /** @enum {string} */
            complianceStatus: "COMPLIANT" | "EXPIRING_SOON" | "NON_COMPLIANT";
        };
        SupplierProfileView: {
            /** Format: uuid */
            id: string;
            legalName: string;
            dbaName?: string | null;
            entityType?: string | null;
            taxIdLast4?: string | null;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            state?: string | null;
            postalCode?: string | null;
            country: string;
            primaryContactName?: string | null;
            primaryContactEmail?: string | null;
            primaryContactPhone?: string | null;
            /** @enum {string} */
            stage: "INVITED" | "REGISTERED" | "PROFILE_SUBMITTED" | "DOCUMENTS_IN_PROGRESS" | "IN_REVIEW" | "CHANGES_REQUESTED" | "APPROVED";
            complete: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        InviteUserBody: {
            /** Format: email */
            email: string;
            fullName: string;
        };
        AcceptRequest: {
            password: string;
        };
        SessionDescription: {
            /** Format: uuid */
            userId: string;
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "OPS" | "PROGRAM_MANAGER" | "SUPPLIER_USER";
            /** Format: uuid */
            supplierId?: string | null;
            supplierName?: string | null;
            programIds: string[];
        };
        SignBody: {
            /** Format: uuid */
            supplierId: string;
            documentTypeCode: string;
            /** Format: uuid */
            enrollmentId?: string | null;
            typedName: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        NewPasswordRequest: {
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        InviteRequest: {
            /** Format: email */
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "OPS" | "PROGRAM_MANAGER" | "SUPPLIER_USER";
            programIds: string[];
        };
        ProfileBody: {
            legalName: string;
            dbaName?: string | null;
            entityType?: string | null;
            taxId?: string | null;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            state?: string | null;
            postalCode?: string | null;
            primaryContactName?: string | null;
            primaryContactEmail?: string | null;
            primaryContactPhone?: string | null;
        };
        RoleRequest: {
            /** @enum {string} */
            role: "ADMIN" | "OPS" | "PROGRAM_MANAGER" | "SUPPLIER_USER";
        };
        ProgramScopeRequest: {
            programIds: string[];
        };
        SupplierSummary: {
            /** Format: uuid */
            id: string;
            legalName: string;
            dbaName?: string | null;
            /** @enum {string} */
            stage: "INVITED" | "REGISTERED" | "PROFILE_SUBMITTED" | "DOCUMENTS_IN_PROGRESS" | "IN_REVIEW" | "CHANGES_REQUESTED" | "APPROVED";
            blocker: components["schemas"]["BlockerView"];
            /** @enum {string} */
            complianceStatus: "COMPLIANT" | "EXPIRING_SOON" | "NON_COMPLIANT";
            programNames: string[];
            primaryContactEmail?: string | null;
            /** Format: date */
            nextExpiry?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        SupplierUserView: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
            status: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        ChecklistEntry: {
            documentTypeCode: string;
            documentTypeName: string;
            description?: string | null;
            /** @enum {string} */
            scope: "SUPPLIER" | "PROGRAM";
            expiring: boolean;
            requiresSignature: boolean;
            classification: string;
            constraints: {
                [key: string]: unknown;
            };
            shared: boolean;
            /** @enum {string} */
            state: "NOT_STARTED" | "IN_REVIEW" | "APPROVED" | "EXPIRING_SOON" | "EXPIRED" | "CHANGES_REQUESTED";
            /** Format: uuid */
            enrollmentId?: string | null;
            submission: components["schemas"]["SubmissionView"] | null;
        };
        ChecklistView: {
            /** Format: uuid */
            supplierId: string;
            legalName: string;
            /** @enum {string} */
            stage: "INVITED" | "REGISTERED" | "PROFILE_SUBMITTED" | "DOCUMENTS_IN_PROGRESS" | "IN_REVIEW" | "CHANGES_REQUESTED" | "APPROVED";
            profileComplete: boolean;
            blocker: components["schemas"]["BlockerView"];
            programs: components["schemas"]["ProgramChecklist"][];
        };
        ProgramChecklist: {
            /** Format: uuid */
            enrollmentId: string;
            /** Format: uuid */
            programId: string;
            programCode: string;
            programName: string;
            programDescription?: string | null;
            enrollmentStatus: string;
            /** @enum {string} */
            complianceStatus: "COMPLIANT" | "EXPIRING_SOON" | "NON_COMPLIANT";
            /** Format: date */
            nextExpiry?: string | null;
            alreadyOnFile: components["schemas"]["ChecklistEntry"][];
            neededForThisProgram: components["schemas"]["ChecklistEntry"][];
        };
        SubmissionView: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            version: number;
            originalFilename: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: date */
            issuedOn?: string | null;
            /** Format: date */
            expiresOn?: string | null;
            /** Format: date-time */
            uploadedAt: string;
            uploadedByName?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            reviewedByName?: string | null;
            rejectionReasonLabel?: string | null;
            rejectionNote?: string | null;
            /** Format: date-time */
            signedAt?: string | null;
            signedBy?: string | null;
        };
        ActivityRow: {
            /** Format: uuid */
            id: string;
            chainKey: string;
            /** Format: int64 */
            sequence: number;
            actorLabel: string;
            action: string;
            subjectType: string;
            /** Format: uuid */
            subjectId?: string | null;
            beforeState?: string | null;
            afterState?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        ProgramRecord: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description?: string | null;
            active: boolean;
        };
        InvitationPreview: {
            email: string;
            /** @enum {string} */
            role: "ADMIN" | "OPS" | "PROGRAM_MANAGER" | "SUPPLIER_USER";
            fullName: string;
            organizationName: string;
            usable: boolean;
            unusableReason?: string | null;
        };
        AgreementPreview: {
            templateVersion: string;
            body: string;
            templateSha256: string;
        };
        DemoAccount: {
            role: string;
            name: string;
            email: string;
            whatTheySee: string;
        };
        DemoInfo: {
            password: string;
            accounts: components["schemas"]["DemoAccount"][];
        };
        StaffUserView: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "OPS" | "PROGRAM_MANAGER" | "SUPPLIER_USER";
            /** @enum {string} */
            status: "INVITED" | "ACTIVE" | "DEACTIVATED";
            programIds: string[];
            /** Format: date-time */
            lastLoginAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSupplierBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierDetail"];
                };
            };
        };
    };
    inviteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteUserBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    upload: {
        parameters: {
            query: {
                documentTypeCode: string;
                enrollmentId?: string;
                issuedOn?: string;
                expiresOn?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionDescription"];
                };
            };
        };
    };
    sign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionDescription"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierProfileView"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierProfileView"];
                };
            };
        };
    };
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramScopeRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierDetail"];
                };
            };
        };
    };
    users: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupplierUserView"][];
                };
            };
        };
    };
    checklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChecklistView"];
                };
            };
        };
    };
    activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityRow"][];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgramRecord"][];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvitationPreview"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    agreement: {
        parameters: {
            query: {
                supplierId: string;
                documentTypeCode: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AgreementPreview"];
                };
            };
        };
    };
    accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DemoInfo"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionDescription"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StaffUserView"][];
                };
            };
        };
    };
    accessHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityRow"][];
                };
            };
        };
    };
}
